"""Find the largest palindrome generated by multiplying 3 digit numbers"""

from solution_set.solution_set import SolutionSet
from mathlib.palindrome import is_palindrome

solution_set = SolutionSet(4, "Find the largest palindrome generated by multiplying 3 digit numbers")

@solution_set.register()
def solution():
    
    found = []
    for i in range(999, 100, -1):
        for k in range(999, 100, -1):
            r = i*k
            if is_palindrome(r):
                found.append(r)
            
    return max(found)

if __name__ == "__main__":
    solution_set.main()

