"""Find the largest palindrome generated by multiplying 3 digit numbers"""

from project_euler.problem.problem import Problem
from mathlib.palindrome import is_palindrome

problem = Problem(4, "Find the largest palindrome generated by multiplying 3 digit numbers")

@problem.register()
def solution():
    
    found = []
    for i in range(999, 100, -1):
        for k in range(999, 100, -1):
            r = i*k
            if is_palindrome(r):
                found.append(r)
            
    return max(found)

if __name__ == "__main__":
    problem.main()

